function show_left_menu()
{
stBM(320,"basic1",[0,"/","","blank.gif",0,"left","default","hand",0,0,-1,-1,-1,"none",0,"#CCCCCC","transparent","","repeat",1,"expand_f.gif","expand_uf.gif",9,9,0,"line_def0.gif","line_def1.gif","line_def2.gif","line_def3.gif",1,0,0,2,"center",0,1,0,"","","","",""]);
stBS("p0",[0,0,"",-2,"",-2,50,-1,3]);
stIT("p0i0",["Home","/index.html","_top","","","","",0,0,"bold 9pt 'Arial'","#1a3065","underline","transparent","","no-repeat","bold 9pt 'Arial'","#006699","underline","transparent","","repeat-x","bold 9pt 'Arial'","#0033FF","underline","transparent","","no-repeat","bold 9pt 'Arial'","#006699","underline","transparent","","no-repeat",1,0,"left","middle",0,0,"","","","",0,0,0]);
stIT("p0i1",["FreeRTOS Books and Manuals","/Documentation/RTOS_book.html",,,,,,,,"9pt 'Arial'",,,,,,"9pt 'Arial'",,,,,"no-repeat",,,,,,,,,,,,,,,,,,,,,,,,,],"p0i0");
stIT("p0i2",["FreeRTOS","/RTOS.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stBS("p1",[,,,,,,,,],"p0");
stIT("p1i0",["About FreeRTOS",,,,,,,,,,,,,,,,,,,,"repeat-x",,,,,,,,,,,,,,,,,,,,,,,,,],"p0i2");
stBS("p2",[,,,,,,,,],"p0");
stIT("p2i0",["What is an RTOS/FreeRTOS?","/about-RTOS.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p2i1",["A Compelling Free Solution",,"_self",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i2");
stIT("p2i2",["A Better Type of Open Source","/open-source-software.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p2i3",["Features Overview","/FreeRTOS_Features.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p2i4",["Coding Standard & Style","/FreeRTOS-Coding-Standard-and-Style-Guide.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p2i5",["Licensing","/a00114.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p2i6",["Site Map","/index.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stES();
stIT("p1i1",["Features / Getting Started...","/FreeRTOS-quick-start-guide.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p1i0");
stBS("p3",[,,,,,,,,],"p0");
stIT("p3i0",["Quick Start Guide","/FreeRTOS-quick-start-guide.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p3i1",["Tasks & Co-routines","/taskandcr.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p3i2",["More About Tasks...","/a00015.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stBS("p4",[,,,,,,,,],"p0");
stIT("p4i0",["Task States","/RTOS-task-states.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p4i1",["Task Priorities","/RTOS-task-priority.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p4i2",["Implementing a Task","/implementing-a-FreeRTOS-task.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p4i3",["Idle Task and Idle Hook","/RTOS-idle-task.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stES();
stIT("p3i3",["More About Co-routines...","/croutine.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stBS("p5",[,,,,,,,,],"p0");
stIT("p5i0",["Co-routine Status","/co-routine-states.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p5i1",["Co-routine Priorities","/co-routine-priorities.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p5i2",["Implementing a Co-routine","/writing-a-FreeRTOS-co-routine.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p5i3",["Scheduling Co-routines","/scheduling-coroutines-with-tasks.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p5i4",["Limitations and Restrictions","/co-routine-limitations.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p5i5",["Quick Co-routine Example","/coroutine-example-code.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p5i6",["Standard Demo Examples","/croutine-standard-demo-examples.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stES();
stIT("p3i4",["Queues, Mutexes, Semaphores...","/Inter-Task-Communication.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stBS("p6",[,,,,,,,,],"p0");
stIT("p6i0",["Queues","/Embedded-RTOS-Queues.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p6i1",["Binary Semaphores","/Embedded-RTOS-Binary-Semaphores.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p6i2",["Counting Semaphores","/Real-time-embedded-RTOS-Counting-Semaphores.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p6i3",["Mutexes","/Real-time-embedded-RTOS-mutexes.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p6i4",["Recursive Mutexes","/RTOS-Recursive-Mutexes.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stES();
stIT("p3i5",["Direct To Task Notifications","/RTOS-task-notifications.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stBS("p7",[,,,,,,,,],"p0");
stIT("p7i0",["Introduction",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p3i5");
stIT("p7i1",["...As Binary Semaphore","/RTOS_Task_Notification_As_Binary_Semaphore.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p7i2",["...As Counting Semaphore","/RTOS_Task_Notification_As_Counting_Semaphore.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p7i3",["...As Event Group","/RTOS_Task_Notification_As_Event_Group.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p7i4",["...As Mailbox","/RTOS_Task_Notification_As_Mailbox.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stES();
stIT("p3i6",["Software Timers","/RTOS-software-timer.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stBS("p8",[,,,,,,,,],"p0");
stIT("p8i0",["Introduction",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p3i6");
stIT("p8i1",["Timer Service Daemon Task","/RTOS-software-timer-service-daemon-task.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p8i2",["Timer Daemon Configuration","/Configuring-a-real-time-RTOS-application-to-use-software-timers.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p8i3",["One-Shot Vs Auto-Reload","/One-shot-Vs-auto-reload-real-time-software-timers.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p8i4",["Resetting a Timer","/Resetting-an-RTOS-software-timer.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stES();
stIT("p3i7",["Event Groups (or \'flags\')","/FreeRTOS-Event-Groups.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p3i8",["Source Code Organisation","/a00017.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stES();
stIT("p1i2",["More Advanced...","/rtos-trace-macros.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p1i0");
stBS("p9",[,,,,,,,,],"p0");
stIT("p9i0",["Creating a New Project","/Creating-a-new-FreeRTOS-project.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p9i1",["FreeRTOSConfig.h","/a00110.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p9i2",["Trace Features","/rtos-trace-macros.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p9i3",["Low Power Support","/low-power-tickless-rtos.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p9i4",["Run Time Stats","/rtos-run-time-stats.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p9i5",["Blocking on Multiple Objects","/Pend-on-multiple-rtos-objects.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p9i6",["Deferred Interrupt Handling","/deferred_interrupt_processing.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p9i7",["Static Vs Dynamic Memory","/Static_Vs_Dynamic_Memory_Allocation.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p9i8",["Memory Management","/a00111.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p9i9",["Memory Protection Support","/FreeRTOS-MPU-memory-protection-unit.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p9i10",["Stack Overflow Protection","/Stacks-and-stack-overflow-checking.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p9i11",["Hook Functions","/a00016.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p9i12",["Thread Local Storage Pointers","/thread-local-storage-pointers.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p9i13",["How FreeRTOS Works","",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stBS("p10",[,,,,,,,,],"p0");
stIT("p10i0",[,"/implementation/main.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p8i0");
stIT("p10i1",["Fundamentals","/implementation/a00002.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stBS("p11",[,,,,,,,,],"p0");
stIT("p11i0",["Multitasking Basics","/implementation/a00004.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p11i1",["Schedulinig Basics","/implementation/a00005.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p11i2",["Context Switching","/implementation/a00006.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p11i3",["Real Time Applications","/implementation/a00007.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p11i4",["Real Time Scheduling","/implementation/a00008.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stES();
stIT("p10i2",["Implementation","/implementation/a00003.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stBS("p12",[,,,,,,,,],"p0");
stIT("p12i0",["Building Blocks","/implementation/a00009.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stBS("p13",[,,,,,,,,],"p0");
stIT("p13i0",["Development Tools","/implementation/a00010.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p13i1",["The RTOS Tick","/implementation/a00011.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p13i2",["GCC Signal Attribute","/implementation/a00012.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p13i3",["GCC Naked Attribute","/implementation/a00013.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p13i4",["FreeRTOS Tick Code","/implementation/a00014.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p13i5",["AVR Context","/implementation/a00015.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p13i6",["Saving the Context","/implementation/a00016.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p13i7",["Restoring the Context","/implementation/a00017.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stES();
stIT("p12i1",["Detailed Example","/implementation/a00018.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stBS("p14",[,,,,,,,,],"p0");
stIT("p14i0",["Putting It All Together","/implementation/a00019.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p14i1",["Step 1","/implementation/a00020.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p14i2",["Step 2","/implementation/a00021.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p14i3",["Step 3","/implementation/a00022.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p14i4",["Step 4","/implementation/a00023.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p14i5",["Step 5","/implementation/a00024.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p14i6",["Step 6","/implementation/a00025.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p14i7",["Step 7","/implementation/a00026.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stES();
stES();
stES();
stIT("p9i14",["RAM Constrained Design Tips","/tutorial/index.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stBS("p15",[,,,,,,,,],"p0");
stIT("p15i0",["Page 1",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p9i14");
stIT("p15i1",["Page 2","/tutorial/solution1.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p15i2",["Page 3","/tutorial/solution2.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p15i3",["Page 4","/tutorial/solution3.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p15i4",["Page 5","/tutorial/solution4.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stES();
stIT("p9i15",["Porting Guide","/FreeRTOS-porting-guide.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p9i16",["Windows Simulator","/FreeRTOS-Windows-Simulator-Emulator-for-Visual-Studio-and-Eclipse-MingW.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p9i17",["Posix/Linux Simulator","/FreeRTOS-simulator-for-Linux.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p9i18",["Legacy Trace Facility","/a00086.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stES();
stIT("p1i3",["Demo Projects","/a00102.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stBS("p16",[,,,,,,,,],"p0");
stIT("p16i0",["Standard Demos",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p1i3");
stIT("p16i1",["Basic Demos","/simple-freertos-demos.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p16i2",["Hardware Independent","/Hardware-independent-RTOS-example.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p16i3",["Modifying a Demo","/porting-a-freertos-demo-to-different-hardware.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p16i4",["TCP/IP Demos","/embeddedtcp.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stES();
stIT("p1i4",["Supported Devices & Demos","/a00090.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p1i0");
stBS("p17",[,,,,,,,,],"p0");
stIT("p17i0",["Official & Contributed Definitions","/differences-between-officially-supported-and-contributed-FreeRTOS-code.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p1i0");
stIT("p17i1",["Simple List of Ports","/RTOS_ports.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p1i0");
stIT("p17i2",["Officially Supported Demos",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p1i4");
stIT("p17i3",[,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p16i4");
stES();
stIT("p1i5",["API Reference","/a00106.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p1i0");
stBS("p18",[,,,,,,,,],"p0");
stIT("p18i0",["PDF Reference Manual","/Documentation/RTOS_book.html","_blank",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p18i1",["Task Creation","/a00019.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stBS("p19",[,,,,,,,,],"p0");
stIT("p19i0",["TaskHandle_t (type)","/a00019.html#xTaskHandle",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p19i1",["xTaskCreate()","/a00125.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p19i2",["xTaskCreateStatic()","/xTaskCreateStatic.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p19i3",["vTaskDelete()","/a00126.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stES();
stIT("p18i2",["Task Control","/a00112.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stBS("p20",[,,,,,,,,],"p0");
stIT("p20i0",["vTaskDelay()","/a00127.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p20i1",["vTaskDelayUntil()","/vtaskdelayuntil.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p20i2",["uxTaskPriorityGet()","/a00128.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p20i3",["vTaskPrioritySet()","/a00129.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p20i4",["vTaskSuspend()","/a00130.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p20i5",["vTaskResume()","/a00131.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p20i6",["xTaskResumeFromISR()","/taskresumefromisr.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p20i7",["xTaskAbortDelay()","/xTaskAbortDelay.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stES();
stIT("p18i3",["Task Utilities","/a00021.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stBS("p21",[,,,,,,,,],"p0");
stIT("p21i0",["uxTaskGetSystemState()","/uxTaskGetSystemState.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p21i1",["vTaskGetInfo()","/vTaskGetInfo.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p21i2",["xTaskGetApplicationTaskTag()","/xTaskGetApplicationTaskTag.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p21i3",["xTaskGetCurrentTaskHandle()","/a00021.html#xTaskGetCurrentTaskHandle",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p21i4",["xTaskGetHandle()","/a00021.html#xTaskGetHandle",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p21i5",["xTaskGetIdleTaskHandle()","/a00021.html#xTaskGetIdleTaskHandle",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p21i6",["uxTaskGetStackHighWaterMark()","/uxTaskGetStackHighWaterMark.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p21i7",["eTaskGetState()","/a00021.html#eTaskGetState",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p21i8",["pcTaskGetName()","/a00021.html#pcTaskGetName",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p21i9",["xTaskGetTickCount()","/a00021.html#xTaskGetTickCount",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p21i10",["xTaskGetTickCountFromISR()","/a00021.html#xTaskGetTickCountFromISR",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p21i11",["xTaskGetSchedulerState()","/a00021.html#xTaskGetSchedulerState",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p21i12",["uxTaskGetNumberOfTasks()","/a00021.html#usTaskGetNumberOfTasks",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p21i13",["vTaskList()","/a00021.html#vTaskList",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p21i14",["vTaskStartTrace()","/a00021.html#vTaskStartTrace",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p21i15",["ulTaskEndTrace()","/a00021.html#usTaskEndTrace",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p21i16",["vTaskGetRunTimeStats()","/a00021.html#vTaskGetRunTimeStats",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p21i17",["vTaskSetApplicationTaskTag()","/vTaskSetApplicationTag.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p21i18",["xTaskCallApplicationTaskHook()","/xTaskCallApplicationTaskHook.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p21i19",["\'SetThreadLocalStoragePointer()","/vTaskSetThreadLocalStoragePointer.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p21i20",["\'GetThreadLocalStoragePointer()","/pvTaskGetThreadLocalStoragePointer.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p21i21",["vTaskSetTimeOutState()","/vTaskSetTimeOutState.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p21i22",["xTaskGetCheckForTimeOut()","/xTaskCheckForTimeOut.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stES();
stIT("p18i4",["RTOS Kernel Control","/a00020.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stBS("p22",[,,,,,,,,],"p0");
stIT("p22i0",["taskYIELD()","/a00020.html#taskYIELD",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p22i1",["taskENTER_CRITICAL()","/taskENTER_CRITICAL_taskEXIT_CRITICAL.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p22i2",["taskEXIT_CRITICAL()",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p22i1");
stIT("p22i3",["taskENTER_CRITICAL_FROM_ISR()","/taskENTER_CRITICAL_FROM_ISR_taskEXIT_CRITICAL_FROM_ISR.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p22i4",["taskEXIT_CRITICAL_FROM_ISR()",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p22i3");
stIT("p22i5",["taskDISABLE_INTERRUPTS()","/a00020.html#taskDISABLE_INTERRUPTS",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p22i6",["taskENABLE_INTERRUPTS()","/a00020.html#taskENABLE_INTERRUPTS",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p22i7",["vTaskStartScheduler()","/a00132.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p22i8",["vTaskEndScheduler()","/a00133.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p22i9",["vTaskSuspendAll()","/a00134.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p22i10",["xTaskResumeAll()","/a00135.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p22i11",["vTaskStepTick()","/vTaskStepTick.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stES();
stIT("p18i5",[,"/RTOS-task-notification-API.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p3i5");
stBS("p23",[,,,,,,,,],"p0");
stIT("p23i0",["xTaskNotifyGive()","/xTaskNotifyGive.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p23i1",["vTaskNotifyGiveFromISR()","/vTaskNotifyGiveFromISR.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p23i2",["ulTaskNotifyTake()","/ulTaskNotifyTake.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p23i3",["xTaskNotify()","/xTaskNotify.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p23i4",["xTaskNotifyAndQuery()","/xTaskNotifyAndQuery.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p23i5",["xTaskNotifyAndQueryFromISR()","/xTaskNotifyAndQueryFromISR.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p23i6",["xTaskNotifyFromISR()","/xTaskNotifyFromISR.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p23i7",["xTaskNotifyWait()","/xTaskNotifyWait.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p23i8",["xTaskNotifyStateClear()","/xTaskNotifyStateClear.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stES();
stIT("p18i6",["FreeRTOS-MPU Specific","/FreeRTOS-MPU-specific.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stBS("p24",[,,,,,,,,],"p0");
stIT("p24i0",["xTaskCreateRestricted()","/xTaskCreateRestricted.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p24i1",["vTaskAllocateMPURegions()","/vTaskAllocateMPURegions.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p24i2",["\'SWITCH_TO_USER_MODE()","/portSWITCH_TO_USER_MODE.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stES();
stIT("p18i7",[,"/a00018.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p6i0");
stBS("p25",[,,,,,,,,],"p0");
stIT("p25i0",["xQueueCreate()","/a00116.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p25i1",["xQueueCreateStatic()","/xQueueCreateStatic.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p25i2",["vQueueDelete()","/a00018.html#vQueueDelete",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p25i3",["xQueueSend()","/a00117.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p25i4",["xQueueSendFromISR()","/a00119.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p25i5",["xQueueSendToBack()","/xQueueSendToBack.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p25i6",["xQueueSendToBackFromISR()","/xQueueSendToBackFromISR.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p25i7",["xQueueSendToFront()","/xQueueSendToFront.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p25i8",["xQueueSendToFrontFromISR()","/xQueueSendToFrontFromISR.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p25i9",["xQueueReceive()","/a00118.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p25i10",["xQueueReceiveFromISR()","/a00120.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p25i11",["uxQueueMessagesWaiting()","/a00018.html#ucQueueMessagesWaiting",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p25i12",["uxQueueMessagesWaitingFromISR()","/a00018.html#ucQueueMessagesWaitingFromISR",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p25i13",["uxQueueSpacesAvailable()","/a00018.html#uxQueueSpacesAvailable",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p25i14",["xQueueReset()","/a00018.html#xQueueReset",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p25i15",["xQueueOverwrite()","/xQueueOverwrite.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p25i16",["xQueueOverwriteFromISR()","/xQueueOverwriteFromISR.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p25i17",["xQueuePeek()","/xQueuePeek.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p25i18",["xQueuePeekFromISR()","/xQueuePeekFromISR.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p25i19",["vQueueAddToRegistry()","/vQueueAddToRegistry.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p25i20",["vQueueUnregisterQueue()","/vQueueUnregisterQueue.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p25i21",["pcQueueGetName()","/pcQueueGetName.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p25i22",["xQueueIsQueueFullFromISR()","/a00018.html#xQueueIsQueueFullFromISR",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p25i23",["xQueueIsQueueEmptyFromISR()","/a00018.html#xQueueIsQueueEmptyFromISR",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stES();
stIT("p18i8",["Queue Sets","/RTOS-queue-sets.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stBS("p26",[,,,,,,,,],"p0");
stIT("p26i0",["xQueueCreateSet()","/xQueueCreateSet.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p26i1",["xQueueAddToSet()","/xQueueAddToSet.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p26i2",["xQueueRemoveFromSet()","/xQueueRemoveFromSet.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p26i3",["xQueueSelectFromSet()","/xQueueSelectFromSet.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p26i4",["xQueueSelectFromSetFromISR()","/xQueueSelectFromSetFromISR.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stES();
stIT("p18i9",["Semaphore / Mutexes","/a00113.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stBS("p27",[,,,,,,,,],"p0");
stIT("p27i0",["xSemaphoreCreateBinary()","/xSemaphoreCreateBinary.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p27i1",["xSemaphoreCreateBinaryStatic()","/xSemaphoreCreateBinaryStatic.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p27i2",["vSemaphoreCreateBinary()","/a00121.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p27i3",["xSemaphoreCreateCounting()","/CreateCounting.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p27i4",["xSemaphoreCreateCountingStatic()","/xSemaphoreCreateCountingStatic.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p27i5",["xSemaphoreCreateMutex()","/CreateMutex.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p27i6",["xSemaphoreCreateMutexStatic()","/xSemaphoreCreateMutexStatic.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p27i7",["xSem\'CreateRecursiveMutex()","/xSemaphoreCreateRecursiveMutex.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p27i8",["xSem\'CreateRecursiveMutexStatic()","/xSemaphoreCreateRecursiveMutexStatic.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p27i9",["vSemaphoreDelete()","/a00113.html#vSemaphoreDelete",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p27i10",["xSemaphoreGetMutexHolder()","/xSemaphoreGetMutexHolder.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p27i11",["uxSemaphoreGetCount()","/uxSemaphoreGetCount.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p27i12",["xSemaphoreTake()","/a00122.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p27i13",["xSemaphoreTakeFromISR()","/xSemaphoreTakeFromISR.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p27i14",["xSemaphoreTakeRecursive()","/xSemaphoreTakeRecursive.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p27i15",["xSemaphoreGive()","/a00123.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p27i16",["xSemaphoreGiveRecursive()","/xSemaphoreGiveRecursive.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p27i17",["xSemaphoreGiveFromISR()","/a00124.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stES();
stIT("p18i10",[,"/FreeRTOS-Software-Timer-API-Functions.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p3i6");
stBS("p28",[,,,,,,,,],"p0");
stIT("p28i0",["xTimerCreate()","/FreeRTOS-timers-xTimerCreate.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p28i1",["xTimerCreateStatic()","/xTimerCreateStatic.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p28i2",["xTimerIsTimerActive()","/FreeRTOS-timers-xTimerIsTimerActive.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p28i3",["xTimerStart()","/FreeRTOS-timers-xTimerStart.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p28i4",["xTimerStop()","/FreeRTOS-timers-xTimerStop.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p28i5",["xTimerChangePeriod()","/FreeRTOS-timers-xTimerChangePeriod.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p28i6",["xTimerDelete()","/FreeRTOS-timers-xTimerDelete.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p28i7",["xTimerReset()","/FreeRTOS-timers-xTimerReset.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p28i8",["xTimerStartFromISR()","/FreeRTOS-timers-xTimerStartFromISR.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p28i9",["xTimerStopFromISR()","/FreeRTOS-timers-xTimerStopFromISR.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p28i10",["xTimerChangePeriodFromISR()","/FreeRTOS-timers-xTimerChangePeriodFromISR.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p28i11",["xTimerResetFromISR()","/FreeRTOS-timers-xTimerResetFromISR.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p28i12",["pvTimerGetTimerID()","/FreeRTOS-timers-pvTimerGetTimerID.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p28i13",["vTimerSetTimerID()","/FreeRTOS-timers-vTimerSetTimerID.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p28i14",["xTimerGetTimerDaemonTaskHandle()","/FreeRTOS-Software-Timer-API-Functions.html#xTimerGetTimerDaemonTaskHandle",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p28i15",["xTimerPendFunctionCall()","/xTimerPendFunctionCall.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p28i16",["xTimerPendFunctionCallFromISR()","/xTimerPendFunctionCallFromISR.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p28i17",["pcTimerGetName()","/FreeRTOS-timers-pcTimerGetName.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p28i18",["xTimerGetPeriod()","FreeRTOS-timers-xTimerGetPeriod.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p28i19",["xTimerGetExpiryTime()","FreeRTOS-timers-xTimerGetExpiryTime.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stES();
stIT("p18i11",[,"/event-groups-API.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p3i7");
stBS("p29",[,,,,,,,,],"p0");
stIT("p29i0",["xEventGroupCreate()","/xEventGroupCreate.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p29i1",["xEventGroupCreateStatic()","/xEventGroupCreateStatic.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p29i2",["vEventGroupDelete()","/vEventGroupDelete.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p29i3",["xEventGroupWaitBits()","/xEventGroupWaitBits.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p29i4",["xEventGroupSetBits()","/xEventGroupSetBits.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p29i5",["xEventGroupSetBitsFromISR()","/xEventGroupSetBitsFromISR.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p29i6",["xEventGroupClearBits()","/xEventGroupClearBits.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p29i7",["xEventGroupClearBitsFromISR()","/xEventGroupClearBitsFromISR.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p29i8",["xEventGroupGetBits()","/xEventGroupGetBits.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p29i9",["xEventGroupGetBitsFromISR()","/xEventGroupGetBitsFromISR.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stIT("p29i10",["xEventGroupSync()","/xEventGroupSync.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p2i1");
stES();
stIT("p18i12",["Co-routines","/croutineapi.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stBS("p30",[,,,,,,,,],"p0");
stIT("p30i0",["CoRoutineHandle_t (type)","/crcreate.html#crhandle",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p30i1",["xCoRoutineCreate()","/crcreate.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p30i2",["crDELAY()","/crdelay.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p30i3",["crQUEUE_SEND()","/crqueuesend.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p30i4",["crQUEUE_RECEIVE()","/crqueuerec.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p30i5",["crQUEUE_SEND_FROM_ISR()","/crsendisr.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p30i6",["crQUEUE_RECEIVE_FROM_ISR()","/crrecisr.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p30i7",["vCoRoutineSchedule()","/crschedule.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stES();
stES();
stIT("p1i6",["Contact, Support, Advertising","/RTOS-contact-and-support.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p1i0");
stBS("p31",[,,,,,,,,],"p0");
stIT("p31i0",["Contact & Advertising","/RTOS-contact-and-support.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p31i1",["Free Support Forum","/FreeRTOS_Support_Forum_Archive/freertos_support_forum_archive_index.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p31i2",["Commercial Support","/RTOS-contact-and-support.html#commercial",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p31i3",["Contract Services","/a00115.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p31i4",["FAQ","/FAQ.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stES();
stES();
stIT("p0i3",["FreeRTOS Interactive!","",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p1i0");
stBS("p32",[,,,,,,,,],"p0");
stIT("p32i0",["Contributed Vs Official Code","/RTOS-contributed-ports.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p32i1",["Contributing Source Code","/Contributing-files-to-FreeRTOS.html",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stIT("p32i2",["Upload / Download Contributions","http://interactive.freertos.org/forums",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"p0i1");
stES();
stES();
stEM();
}

